
#pipelines = workflows

name: Urdhva Docker Deployment

on:
  push: 
    branches:
      - development  #branch_1
      - UAT          #branch_2
      - main         #branch_3

#optional
env:
  Source_name: urdhva-app
  deploy_name: docker-workflow

jobs:
  - name: findout developers
    if (branch_name = development and sourcename= urdhva-app and docker-workflow) then
    steps:
      - finding architect
      - finding senior developer
      - finding juniors

  - name: findout databases
    if (branch_name = development and sourcename= urdhva-app) then
    steps:
      - finding correct database
      - finding storage capacity

  - name: findout where to host
    if (branch_name = development and sourcename= urdhva-app) then

  - name: findout QA
    if (branch_name = UAT and sourcename= urdhva-app and docker-workflow) then

  - name: findout userbase

  - name: findout accessories for shopping
    if (branch_name = development and sourcename= urdhva-app and docker-workflow) then
